### ISSUE TITLE
Failing for Google+ 

### ISSUE THREAD

**Issue by hutton** [crhym3/simpleauth#37]
Logging into Google+ from https://simpleauth.appspot.com/ fails with:

"ValueError: No JSON object could be decoded".

![image](https://cloud.githubusercontent.com/assets/162255/6508721/5c7d7c3a-c352-11e4-96c6-170a8c829434.png)

I get the same error when using SimpleAuth in my own project, stacktrace below.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~migraine-view/9.382668147855496066/app/authentication.py", line 32, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~migraine-view/9.382668147855496066/libs/simpleauth/handler.py", line 179, in _auth_callback
    result = meth(provider, *cfg[-1:])
  File "/base/data/home/apps/s~migraine-view/9.382668147855496066/libs/simpleauth/handler.py", line 279, in _oauth2_callback
    auth_info = _parser(resp.content)
  File "/base/data/home/apps/s~migraine-view/9.382668147855496066/libs/simpleauth/handler.py", line 580, in _json_parser
    return json.loads(body)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by crhym3** [comment]
I believe it's an on-going issue with Auth on App Engine. Please follow this thread:
https://groups.google.com/d/topic/google-appengine-downtime-notify/fxhUJgjDZfA/discussion

**Comment by hutton** [comment]
Thanks for the quick feedback.  Looks like the issue is resolved now.
